_data/poems/xli-poems/songs-ix.yaml
Wasn't sure precisely how much spacing to use on the two indented lines to be displayed most accurately, feel free to change!
=> Add text for Lady of Silence

_data/poems/tulips-and-chimneys/epithalamion.yaml
=> Corrections to Epithalamion transcription

_data/poems/xli-poems/la-guerre-i.yaml, _data/poems/xli-poems/la-guerre-ii.yaml
Hope I did this right! And that I transcribed the version/edition you want? 
If I want to help further, should I buy [this exact book](https://www.amazon.com/gp/product/1631490419/ref=ox_sc_act_image_1?smid=ATVPDKIKX0DER&psc=1)?
=> Keypunches La Guerre I and II

_data/poems/xli-poems/sonnets-ii.yaml, _data/poems/xli-poems/sonnets-iv.yaml, _data/poems/xli-poems/sonnets-v.yaml, _data/poems/xli-poems/sonnets-vi.yaml
I'm not sure how you want to handle long dashes or lines the contain colons. I copy and pasted an emdash from the web. 
For the colon question, I followed your lead on Songs II by _not_ putting lines with colons in single quotes. However, one line in Sonnets VI starts with an emdash and ends with a colon. My text editor kept wanting to indent that particular line 0 or 2 spaces, rather than 1 space, so I just put that one in single quotes. 
I worked from [this scan](https://babel.hathitrust.org/cgi/pt?id=uc1.$b408727&view=1up&seq=50), which you linked to [here](https://github.com/ee-cummings-archive/cummings.ee/issues/37#issuecomment-831321536).
=> Keypunches Sonnets 2, 4, 5, and 6

_data/poems/xli-poems/la-guerre-ii.yaml
In case this is how you want to handle apostrophes.
=> Uses curly (smart) apostrophes throughout La Guerre II

_data/books.yaml
=> Fix typo in description of XLI Poems

_data/poems/xli-poems/sonnets-x.yaml
=> Keypunches Sonnets X

_data/poems/xli-poems/sonnets-xi.yaml
Hope it's OK that I'm doing one PR per poem -- I'm just using the GitHub web UI today.
=> Keypunches Sonnets XI

_data/poems/xli-poems/sonnets-xvi.yaml
=> Keypunches Sonnets XVI

_data/poems/xli-poems/songs-iii.yaml
There looks to be a space before the apostrophe s on line 6, so I have entered it as such
=> XLI Poems Songs III

_data/poems/xli-poems/portraits-ii.yaml
In case #64 isn't adequate, due to that pesky first commit.
I did my best with the Greek(?)
=> Keypunches Portraits II

_data/poems/xli-poems/portraits-i.yaml
In case #64 doesn't work for you, due to its first commit.
=> Keypunches Portraits I

_data/poems/xli-poems/songs-viii.yaml, _data/poems/xli-poems/songs-x.yaml, _data/poems/xli-poems/songs-xi.yaml, _data/poems/xli-poems/songs-xii.yaml
I don't know how many of these I'm going to key in, but I figured I'd make the PR in case anyone else is looking at doing any. I started with "Songs VIII" and I'm going to keep on in order.
=> Poems from XLI Poems

_data/poems/and/post-impressions-iv.yaml, _data/poems/and/post-impressions-ix.yaml, _data/poems/and/post-impressions-vi.yaml, _data/poems/and/post-impressions-vii.yaml, _data/poems/and/post-impressions-viii.yaml
On this branch I'm going to key in poems from & (see #35).
I checked out [the Internet Archive edition of Harcourt’s "Poems”](https://archive.org/details/poems192319540913cumm/page/75/mode/1up) to use as a reference.
=> Keypunch & - Post Impressions IV - IX

_data/poems/and/sonnets-realities-xi.yaml
From page 137 of Complete Poems
=> keypunches and sonnets-realities 11

_data/poems/and/sonnets-realities-xiii.yaml
=> keypunches and sonnets-realities 13

_data/poems/and/sonnets-realities-xv.yaml
=> keypunches and sonnets-realities 15

_data/poems/and/sonnets-realities-xvii.yaml
=> keypunches and sonnets-realities 17

_data/poems/and/sonnets-realities-xviii.yaml
Feeling a little rusty today so might have missed some small stuff?
=> keypunches and sonnets-realities 18

_data/poems/and/portraits-i.yaml
Opening PRs on branches, if that's preferred. :)
=> Added &, Portraits I, being

_data/poems/and/portraits-ii.yaml
=> Rwhite5279 and portraits ii

_data/poems/and/portraits-iii.yaml
=> Rwhite5279 and portraits iii

_data/poems/and/portraits-xii.yaml
Starting to work from the end of the Portraits now to avoid collisions. :)
=> Added &, Portraits XII, little ladies more

_data/poems/and/post-impressions-x.yaml, _data/poems/and/post-impressions-xi.yaml, _data/poems/and/post-impressions-xii.yaml, _data/poems/and/post-impressions-xiii.yaml, _data/poems/and/post-impressions-xiv.yaml
All five poems transcribed from Firmage's 1994 Edition "e. e. cummings Complete Poems 1904-1962".
=> & Post Impressions X through XIV

_data/poems/is-5/five-americans-ii.yaml
And here's what I'm _pretty sure_ is five-americans-ii. Would be worth double-checking, as I might have gotten confused in this git mess.
=> re-adds is 5 five americans ii

_data/poems/is-5/five-americans-ii.yaml, _data/poems/is-5/five-americans-iii.yaml, _data/poems/is-5/five-americans-iv.yaml, _data/poems/is-5/five-americans-v.yaml
Thanks for making the repo less chonky, happy to resubmit! 😃
=> Five Americans ii through v.

_data/poems/is-5/one-xl.yaml, _layouts/poem_detail.html, styles/components/_poem.scss
This PR adds the poem "life hurl my" and a helper class `.rotate` for vertical left-to-right alignment. I haven't proofed the text fully so consider this a in-progress PR.
=> Life hurl my

_data/poems/is-5/one-xx.yaml, _data/poems/is-5/one-xxxiii.yaml, _data/poems/is-5/one-xxxiv.yaml
=> Three more poems

_data/poems/is-5/two-v.yaml, _data/poems/is-5/two-vi.yaml, _data/poems/is-5/two-vii.yaml, _data/poems/is-5/two-viii.yaml
=> keypunches is 5 Two v through viii

_data/poems/and/post-impressions-viii.yaml, _data/poems/and/post-impressions-x.yaml, _data/poems/and/post-impressions-xi.yaml, _data/poems/and/sonnets-actualities-xxiii.yaml, _data/poems/is-5/four-vii.yaml, _data/poems/tulips-and-chimneys/chansons-innocentes-ii.yaml, _data/poems/tulips-and-chimneys/epithalamion.yaml, _data/poems/tulips-and-chimneys/of-nicolette.yaml, _data/poems/xli-poems/sonnets-viii.yaml, _data/poems/xli-poems/sonnets-xii.yaml
=> replaces some 'straight' apostrophes with curly ones

_data/poems/is-5/two-ii.yaml
=> keypunches is 5 two ii

_data/poems/is-5/four-xvi.yaml
Completed assigned task to transcribe four-xvi
=> Transcribed four-xvi (Fixes #184)

_data/poems/is-5/one-xviii.yaml
Transcribed as bonus contribution.
=> Transcribed (Fixes #202)

_data/poems/is-5/five-iv.yaml
@palewire, hope this was an accurate transcription of the poem.
=> entered "our touching hears slenderly comprehend" Fixes #187

_data/poems/is-5/four-xiii.yaml
Ben, 
Got about a third of the way through "Nobody wears a yellow" before you called time. Enjoyed the class. Hope to see you at NICAR. //ron
=> wrote a third of the poem -- Fixes #182

styles/components/_container.scss
Tentative fix to issue overflow-x in Chrome.
=> Hide overflow-x explicitly (Fixes #133)

_data/toc/is-5.json
=> Add the FORWARD to 'is 5'

_layouts/book_detail.html
=> Too much margin beneath the "is 5" Forward

_layouts/book_detail.html, styles/components/_toc.scss
=> Long Roman numerals are clipping in "is 5" table of contents

_data/poems/is-5/one-x.yaml
=> ONE X: death is more than

_data/poems/is-5/one-viii.yaml
=> ONE VIII: isten my children and you

_data/poems/is-5/one-xxviii.yaml
=> Transcription of "my uncle". Fixes #192

_data/poems/is-5/one-xxxv.yaml
=> entered 1 XXXV

_data/poems/is-5/four-xvii.yaml
=> Enter "how this uncouth enchanted"

_data/poems/is-5/five-i.yaml
=> Enter "after all white horses are in bed"

_data/poems/is-5/four-xi.yaml, styles/components/_poem.scss
=> Enter "because"

_data/poems/is-5/three-iv.yaml, styles/components/_poem.scss
=> Added "impossibly"

_data/poems/is-5/five-v.yaml
Unsure if I indented correctly on line 12 or if the end of line 13 is a colon or semi-colon.
=> Transcription of "if i have made,my lady,intricate" Fixes #266

_data/poems/is-5/one-xvi.yaml
=> Added "it started when Bill’s chip let on to"

_data/poems/is-5/one-xix.yaml
=> Added "this young question mark man"

_data/poems/is-5/one-xxvi.yaml
=> Added "on the Madam’s best april the"

_data/poems/is-5/one-xxxii.yaml
=> Added "a man who had fallen among thieves"

_data/poems/is-5/one-xxii.yaml, styles/components/_poem.scss
=> Added "she being Brand"

_data/poems/is-5/one-xxxix.yaml
Not sure if there is a space after the semicolon on line 32!
=> Transcription of "voices to voices,lip to lip" Fixes #246

_data/poems/is-5/four-iii.yaml
This was a tough one. I couldn't quite make out the first character on line 25 and the punctuation after the second parenthesis on line 32. Sorry if there are a few other typographical errors.
=> Transcription of "here's a little mouse)and" Fixes #258

_data/poems/is-5/four-vi.yaml
=> Enter "you are not going to,dear. You are not going to and"

_data/poems/is-5/four-xii.yaml
=> Enter "you being in love"

_data/poems/is-5/four-xv.yaml
=> Enter "i am a beggar always"

_data/poems/is-5/three-x.yaml
=> Enter "sunlight was over"

_data/poems/is-5/three-ix.yaml, styles/components/_poem.scss
=> Enter "but observe;although"

_data/poems/is-5/three-viii.yaml, styles/components/_poem.scss
Fixes #255
This one is going to need an expert opinion on how we handle the linebreaks.
=> Enter "will out of the kindness of their hearts a few philoso-phers tell me"

_data/poems/is-5/three-vi.yaml, styles/components/_poem.scss
=> Enter "candles and"

_data/poems/is-5/three-iii.yaml
=> Enter "it is winter a moon in the afternoon"

_data/poems/is-5/two-xi.yaml
=> Enter "my sweet old etcetera"

_data/poems/is-5/two-x.yaml, styles/components/_poem.scss
=> Enter "16 heures"

_data/poems/is-5/one-xxxviii.yaml, styles/components/_poem.scss
Fixes #245
Here I think we need too look at if we should put an indent on the front of each paragraph.
=> Enter "Will i ever forget that precarious moment?"

_data/poems/is-5/one-vi.yaml, styles/components/_poem.scss
I think I worked out how to insert unicode properly after finding your existing example in this file - will go back and fix previous patch (hopefully before you see it).
=> Transcription of "Jimmie's got a goil" Fixes #234

_data/poems/is-5/forward.yaml
I think I got the spacing right - sometimes it seems to run together, but I think it's just the spacing in the fully justified page.
I'm not sure about how to represent the colon in line 33 (it tries to convert the preceeding text into a key) . After some googling I used the unicode decimal, but I'm suspicious it isn't going to convert properly. Feedback on this would be great. Completely new to YAML.
=> Transcription of Forward to "is 5". Fixes #295

_data/poems/and/sonnets-actualities-xxiii.yaml, _data/poems/is-5/five-ii.yaml, _data/poems/is-5/four-iii.yaml
=> makes some straight apostrophes and double quotes curly 
